OrdererOrgs:
 - Name: Orderer
   Domain: pharma.net
   Specs:
      - Hostname: orderer

PeerOrgs:
 - Name: manufacturer
   Domain: manufacturer.pharma.net
   EnableNodeOUs: true
   CA:
      Hostname: ca
   Template:
      Count: 2
   # Users:
   #    Count: 1

 - Name: distributor
   Domain: distributor.pharma.net
   EnableNodeOUs: true
   CA:
      Hostname: ca
   Template:
      Count: 2
   # Users:
   #    Count: 1

 - Name: retailer
   Domain: retailer.pharma.net
   EnableNodeOUs: true
   CA:
      Hostname: ca
   Template:
      Count: 2
   # Users:
   #    Count: 1

 - Name: transporter
   Domain: transporter.pharma.net
   EnableNodeOUs: true
   CA:
     Hostname: ca
   Template:
     Count: 2
   # Users:
   #   Count: 1


 # - Name: consumer
 #   Domain: consumer.pharma.net
 #   EnableNodeOUs: true
 #   CA:
 #     Hostname: ca
 #   Template:
 #     Count: 2
 #   Users:
 #     Count: 1
 #
